language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - RUSTFLAGS="-D warnings"
jobs:
  fast_finish: true
cache: cargo
script:
  - cargo check
  - cargo test --lib
before_install:
  - sudo apt-get -y install xorg-dev
